### ISSUE TITLE
Poison training macro fix post shelf update

### ISSUE THREAD

**Issue by Toldwin** [jaseowns/uo_outlands_razor_scripts#5]
Hi mate ! 

Thanks for your great work ! 

Sorry to use an issue to contact you but I tough it was a better option than to make a fork...

I fixed the gump id for the new shelf... I had to remove the restock because i don't know why if I let it's only working half the time and I really have no idear why. BTW it's working properly without the restock so I think you could update it like this.

No obligation to take this into acount but it was a way for me to thank you for your work.

Best regards !

[updated poison training with shelf.txt](https://github.com/jaseowns/uo_outlands_razor_scripts/files/11240677/updated.poison.training.with.shelf.txt)

**Comment by jaseowns** [comment]
Thanks @Toldwin - the site was updated but not github.  I will update
https://outlands.uorazorscripts.com/skills/poisoning/c719ac6d-2ef8-4e31-9834-700b84dc85c2
